# Generated by Django 4.1.4 on 2022-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_rentlog_rentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Accept', 'Accepted'), ('Reject', 'Rejected')], max_length=10),
        ),
    ]
