# Generated by Django 4.1.4 on 2022-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_alter_rentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentlog',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
